export const resumeSections = [
  'personal',
  'jobPreference',
  'education',
  'employment',
  'project',
  'research',
  'language',
  'skill',
  'certificate',
  'award',
  'campus',
  'volunteer',
  'training',
  'portfolio',
  'intellectualProperty',
  'referee',
  'compliance',
] as const;

export type ResumeSection = (typeof resumeSections)[number];
export type FieldValueKind =
  | 'attachment'
  | 'boolean'
  | 'date'
  | 'dateRange'
  | 'number'
  | 'stringList'
  | 'text'
  | 'url';
export type Sensitivity = 'normal' | 'sensitive' | 'highlySensitive';
export type FieldAvailability = 'mvp' | 'deferred';

export interface FieldDefinition {
  label: string;
  section: ResumeSection;
  kind: FieldValueKind;
  sensitivity: Sensitivity;
  availability: FieldAvailability;
  variantOverride: boolean;
}

const field = (
  label: string,
  section: ResumeSection,
  kind: FieldValueKind = 'text',
  sensitivity: Sensitivity = 'normal',
  availability: FieldAvailability = 'mvp',
  variantOverride = false,
): FieldDefinition => ({
  label,
  section,
  kind,
  sensitivity,
  availability,
  variantOverride,
});

export const fieldCatalog = {
  'personal.photo': field('简历照片', 'personal', 'attachment', 'sensitive'),
  'personal.fullName': field('姓名', 'personal'),
  'personal.namePinyin': field('姓名拼音', 'personal'),
  'personal.englishName': field('英文名', 'personal'),
  'personal.gender': field('性别', 'personal', 'text', 'sensitive'),
  'personal.birthDate': field('出生日期', 'personal', 'date', 'sensitive'),
  'personal.currentCity': field('所在城市', 'personal'),
  'personal.hometown': field('籍贯', 'personal', 'text', 'sensitive'),
  'personal.phone': field('手机号码', 'personal', 'text', 'sensitive'),
  'personal.email': field('邮箱地址', 'personal', 'text', 'sensitive'),
  'personal.graduationDate': field('预计/实际毕业时间', 'personal', 'date'),
  'personal.github': field('GitHub URL/ID', 'personal', 'url'),
  'personal.countryRegion': field('国家/地区', 'personal'),
  'personal.nationality': field('国籍', 'personal', 'text', 'sensitive'),
  'personal.ethnicity': field('民族', 'personal', 'text', 'sensitive'),
  'personal.politicalStatus': field(
    '政治面貌',
    'personal',
    'text',
    'sensitive',
  ),
  'personal.maritalStatus': field(
    '婚姻状况',
    'personal',
    'text',
    'highlySensitive',
    'deferred',
  ),
  'personal.heightCm': field(
    '身高',
    'personal',
    'number',
    'sensitive',
    'deferred',
  ),
  'personal.identityDocument': field(
    '身份证件',
    'personal',
    'text',
    'highlySensitive',
    'deferred',
  ),
  'personal.householdRegistration': field(
    '户口信息',
    'personal',
    'text',
    'highlySensitive',
    'deferred',
  ),
  'personal.currentAddress': field('当前地址', 'personal', 'text', 'sensitive'),
  'personal.familyAddress': field(
    '家庭地址',
    'personal',
    'text',
    'highlySensitive',
    'deferred',
  ),
  'personal.emergencyContact': field(
    '紧急联系人',
    'personal',
    'text',
    'highlySensitive',
    'deferred',
  ),
  'personal.wechat': field('微信号', 'personal', 'text', 'sensitive'),
  'personal.personalSite': field('个人主页/博客', 'personal', 'url'),
  'personal.linkedin': field('LinkedIn', 'personal', 'url'),
  'personal.gitee': field('Gitee', 'personal', 'url'),
  'personal.portfolioSite': field('作品集主页', 'personal', 'url'),
  'personal.summary': field(
    '个人简介/自我评价',
    'personal',
    'text',
    'normal',
    'mvp',
    true,
  ),
  'personal.strengths': field(
    '个人优势/关键词',
    'personal',
    'stringList',
    'normal',
    'mvp',
    true,
  ),
  'personal.currentStatus': field('当前身份', 'personal'),
  'personal.firstWorkDate': field('首次参加工作时间', 'personal', 'date'),

  'jobPreference.position': field(
    '申请职位',
    'jobPreference',
    'text',
    'normal',
    'mvp',
    true,
  ),
  'jobPreference.positionCode': field(
    '职位编号',
    'jobPreference',
    'text',
    'normal',
    'mvp',
    true,
  ),
  'jobPreference.positionCategory': field(
    '职位类别',
    'jobPreference',
    'text',
    'normal',
    'mvp',
    true,
  ),
  'jobPreference.cities': field(
    '期望工作城市',
    'jobPreference',
    'stringList',
    'normal',
    'mvp',
    true,
  ),
  'jobPreference.acceptLocationTransfer': field(
    '接受地点调剂',
    'jobPreference',
    'boolean',
    'normal',
    'mvp',
    true,
  ),
  'jobPreference.department': field(
    '期望部门',
    'jobPreference',
    'text',
    'normal',
    'mvp',
    true,
  ),
  'jobPreference.salary': field(
    '期望薪资',
    'jobPreference',
    'text',
    'sensitive',
    'mvp',
    true,
  ),
  'jobPreference.availableDate': field(
    '可入职时间',
    'jobPreference',
    'date',
    'normal',
    'mvp',
    true,
  ),
  'jobPreference.applicationType': field(
    '求职类型',
    'jobPreference',
    'text',
    'normal',
    'mvp',
    true,
  ),
  'jobPreference.workMode': field(
    '工作性质',
    'jobPreference',
    'text',
    'normal',
    'mvp',
    true,
  ),
  'jobPreference.acceptTravel': field(
    '接受出差',
    'jobPreference',
    'boolean',
    'normal',
    'mvp',
    true,
  ),
  'jobPreference.acceptSpecialSchedule': field(
    '接受加班/轮班/驻场',
    'jobPreference',
    'boolean',
    'sensitive',
    'mvp',
    true,
  ),
  'jobPreference.acceptRemote': field(
    '接受远程办公',
    'jobPreference',
    'boolean',
    'normal',
    'mvp',
    true,
  ),
  'jobPreference.internshipDuration': field(
    '实习持续时长',
    'jobPreference',
    'text',
    'normal',
    'mvp',
    true,
  ),
  'jobPreference.daysPerWeek': field(
    '每周实习天数',
    'jobPreference',
    'number',
    'normal',
    'mvp',
    true,
  ),

  'education.school': field('学校名称', 'education'),
  'education.dateRange': field('起止时间', 'education', 'dateRange'),
  'education.major': field('专业', 'education'),
  'education.educationLevel': field('学历', 'education'),
  'education.degree': field('学位', 'education'),
  'education.gpa': field('GPA', 'education', 'number'),
  'education.gpaScale': field('GPA 满分制', 'education', 'number'),
  'education.rank': field('GPA/专业排名', 'education'),
  'education.rankTotal': field('年级总人数', 'education', 'number'),
  'education.fullTime': field('是否全日制', 'education', 'boolean'),
  'education.laboratory': field('实验室', 'education'),
  'education.advisor': field('导师', 'education', 'text', 'sensitive'),
  'education.researchDirection': field('研究方向', 'education'),
  'education.department': field('学院/院系', 'education'),
  'education.location': field('学校所在地', 'education'),
  'education.duration': field('学制', 'education'),
  'education.highest': field('是否最高学历', 'education', 'boolean'),
  'education.admissionType': field('入学方式/招生批次', 'education'),
  'education.courses': field('主修课程', 'education', 'stringList'),
  'education.minor': field('辅修专业', 'education'),
  'education.doubleDegree': field('双学位', 'education'),
  'education.exchangeExperience': field('交换经历', 'education'),
  'education.thesis': field('毕业论文/课题', 'education'),
  'education.description': field('教育经历描述', 'education'),

  'employment.company': field('公司名称', 'employment'),
  'employment.dateRange': field('起止时间', 'employment', 'dateRange'),
  'employment.position': field('职位名称', 'employment'),
  'employment.description': field(
    '工作描述',
    'employment',
    'text',
    'normal',
    'mvp',
    true,
  ),
  'employment.location': field('公司所在地', 'employment'),
  'employment.department': field('部门/团队', 'employment'),
  'employment.positionCategory': field('职位类别', 'employment'),
  'employment.experienceType': field('经历类型', 'employment'),
  'employment.industry': field('所属行业', 'employment'),
  'employment.manager': field('汇报对象', 'employment', 'text', 'sensitive'),
  'employment.current': field('是否在职', 'employment', 'boolean'),
  'employment.leaveReason': field(
    '离职原因',
    'employment',
    'text',
    'sensitive',
  ),
  'employment.achievements': field(
    '工作成果',
    'employment',
    'stringList',
    'normal',
    'mvp',
    true,
  ),
  'employment.technologies': field(
    '技术栈/工具',
    'employment',
    'stringList',
    'normal',
    'mvp',
    true,
  ),
  'employment.reference': field(
    '证明人',
    'employment',
    'text',
    'highlySensitive',
    'deferred',
  ),

  'project.name': field('项目名称', 'project'),
  'project.role': field('项目角色', 'project'),
  'project.dateRange': field('起止时间', 'project', 'dateRange'),
  'project.url': field('项目链接', 'project', 'url'),
  'project.summary': field(
    '项目背景/简介',
    'project',
    'text',
    'normal',
    'mvp',
    true,
  ),
  'project.responsibilities': field(
    '个人职责',
    'project',
    'stringList',
    'normal',
    'mvp',
    true,
  ),
  'project.technologies': field(
    '技术栈',
    'project',
    'stringList',
    'normal',
    'mvp',
    true,
  ),
  'project.achievements': field(
    '项目成果',
    'project',
    'stringList',
    'normal',
    'mvp',
    true,
  ),
  'project.teamSize': field('团队规模', 'project', 'number'),
  'project.openSource': field('是否开源', 'project', 'boolean'),
  'project.repository': field('代码仓库', 'project', 'url'),

  'research.title': field('论文/成果名称', 'research'),
  'research.type': field('论文类型', 'research'),
  'research.venue': field('期刊/会议', 'research'),
  'research.level': field('期刊/会议等级', 'research'),
  'research.status': field('发表状态', 'research'),
  'research.publishedDate': field('发表时间', 'research', 'date'),
  'research.authorOrder': field('作者顺序', 'research', 'number'),
  'research.correspondingAuthor': field('是否通讯作者', 'research', 'boolean'),
  'research.url': field('DOI/论文链接', 'research', 'url'),
  'research.abstract': field('摘要', 'research', 'text', 'normal', 'mvp', true),
  'research.contribution': field(
    '研究职责与成果',
    'research',
    'text',
    'normal',
    'mvp',
    true,
  ),

  'language.name': field('语言类型', 'language'),
  'language.proficiency': field('掌握程度', 'language'),
  'language.exam': field('考试名称', 'language'),
  'language.score': field('分数', 'language'),
  'language.examDate': field('考试时间', 'language', 'date'),
  'language.listening': field('听力水平', 'language'),
  'language.speaking': field('口语水平', 'language'),
  'language.reading': field('阅读水平', 'language'),
  'language.writing': field('写作水平', 'language'),

  'skill.name': field('技能名称', 'skill'),
  'skill.category': field('技能分类', 'skill'),
  'skill.proficiency': field('熟练程度', 'skill'),
  'skill.years': field('使用年限', 'skill', 'number'),

  'certificate.name': field('证书名称', 'certificate'),
  'certificate.number': field('证书编号', 'certificate', 'text', 'sensitive'),
  'certificate.issuer': field('颁发机构', 'certificate'),
  'certificate.issuedDate': field('获取时间', 'certificate', 'date'),
  'certificate.expiryDate': field('到期时间', 'certificate', 'date'),
  'certificate.attachment': field(
    '证书附件',
    'certificate',
    'attachment',
    'sensitive',
  ),

  'award.name': field('奖项/竞赛名称', 'award'),
  'award.level': field('获奖等级', 'award'),
  'award.organizer': field('主办方', 'award'),
  'award.date': field('获奖时间', 'award', 'date'),
  'award.scope': field('获奖范围', 'award'),
  'award.teamType': field('个人奖/团队奖', 'award'),
  'award.rank': field('排名', 'award'),
  'award.contribution': field('角色与贡献', 'award'),
  'award.description': field('经历描述', 'award'),
  'award.attachment': field('证明材料', 'award', 'attachment', 'sensitive'),

  'campus.organization': field('组织/社团名称', 'campus'),
  'campus.position': field('职务', 'campus'),
  'campus.dateRange': field('起止时间', 'campus', 'dateRange'),
  'campus.description': field('经历描述', 'campus'),
  'campus.responsibilities': field('主要职责', 'campus', 'stringList'),
  'campus.achievements': field('成果', 'campus', 'stringList'),

  'volunteer.organization': field('组织名称', 'volunteer'),
  'volunteer.activity': field('活动/项目名称', 'volunteer'),
  'volunteer.role': field('角色', 'volunteer'),
  'volunteer.dateRange': field('起止时间', 'volunteer', 'dateRange'),
  'volunteer.hours': field('服务时长', 'volunteer', 'number'),
  'volunteer.description': field('经历描述', 'volunteer'),
  'volunteer.achievements': field('成果', 'volunteer', 'stringList'),

  'training.name': field('培训名称', 'training'),
  'training.organization': field('培训机构', 'training'),
  'training.dateRange': field('起止时间', 'training', 'dateRange'),
  'training.content': field('培训内容', 'training'),
  'training.certificate': field('获得证书', 'training'),

  'portfolio.name': field(
    '作品名称',
    'portfolio',
    'text',
    'normal',
    'mvp',
    true,
  ),
  'portfolio.type': field(
    '作品类型',
    'portfolio',
    'text',
    'normal',
    'mvp',
    true,
  ),
  'portfolio.urls': field(
    '作品链接',
    'portfolio',
    'stringList',
    'normal',
    'mvp',
    true,
  ),
  'portfolio.description': field(
    '作品简介',
    'portfolio',
    'text',
    'normal',
    'mvp',
    true,
  ),
  'portfolio.contribution': field(
    '个人职责',
    'portfolio',
    'text',
    'normal',
    'mvp',
    true,
  ),
  'portfolio.attachments': field(
    '图片/视频/附件',
    'portfolio',
    'stringList',
    'sensitive',
    'mvp',
    true,
  ),
  'portfolio.repository': field(
    '代码仓库',
    'portfolio',
    'url',
    'normal',
    'mvp',
    true,
  ),
  'portfolio.stars': field(
    '最高 Star 数',
    'portfolio',
    'number',
    'normal',
    'mvp',
    true,
  ),
  'portfolio.forks': field(
    'Fork 数',
    'portfolio',
    'number',
    'normal',
    'mvp',
    true,
  ),
  'portfolio.downloads': field(
    '下载量',
    'portfolio',
    'number',
    'normal',
    'mvp',
    true,
  ),
  'portfolio.users': field(
    '用户量',
    'portfolio',
    'number',
    'normal',
    'mvp',
    true,
  ),

  'intellectualProperty.name': field('专利/软著名称', 'intellectualProperty'),
  'intellectualProperty.type': field('类型', 'intellectualProperty'),
  'intellectualProperty.number': field('申请号/授权号', 'intellectualProperty'),
  'intellectualProperty.appliedDate': field(
    '申请时间',
    'intellectualProperty',
    'date',
  ),
  'intellectualProperty.grantedDate': field(
    '授权时间',
    'intellectualProperty',
    'date',
  ),
  'intellectualProperty.status': field('当前状态', 'intellectualProperty'),
  'intellectualProperty.inventorOrder': field(
    '发明人顺序',
    'intellectualProperty',
    'number',
  ),
  'intellectualProperty.url': field('相关链接', 'intellectualProperty', 'url'),
  'intellectualProperty.description': field('简介', 'intellectualProperty'),

  'referee.name': field('推荐人姓名', 'referee', 'text', 'sensitive'),
  'referee.relationship': field('与本人关系', 'referee', 'text', 'sensitive'),
  'referee.organization': field('公司/学校', 'referee', 'text', 'sensitive'),
  'referee.position': field('职务', 'referee', 'text', 'sensitive'),
  'referee.phone': field('电话', 'referee', 'text', 'highlySensitive'),
  'referee.email': field('邮箱', 'referee', 'text', 'highlySensitive'),
  'referee.permission': field(
    '已获联系许可',
    'referee',
    'boolean',
    'sensitive',
  ),

  'compliance.relativesAtCompany': field(
    '亲属在目标公司任职',
    'compliance',
    'boolean',
    'highlySensitive',
    'deferred',
  ),
  'compliance.previousEmployment': field(
    '曾在目标公司工作/实习',
    'compliance',
    'boolean',
    'sensitive',
  ),
  'compliance.nonCompete': field(
    '签署竞业限制',
    'compliance',
    'boolean',
    'sensitive',
  ),
  'compliance.needsVisaSupport': field(
    '需要签证支持',
    'compliance',
    'boolean',
    'sensitive',
  ),
  'compliance.workAuthorization': field(
    '工作许可',
    'compliance',
    'text',
    'highlySensitive',
    'deferred',
  ),
  'compliance.backgroundCheck': field(
    '接受背景调查',
    'compliance',
    'boolean',
    'sensitive',
  ),
  'compliance.source': field('招聘信息来源', 'compliance'),
  'compliance.referral': field(
    '内推人/内推码',
    'compliance',
    'text',
    'sensitive',
  ),
} as const satisfies Record<string, FieldDefinition>;

export type ResumeFieldId = keyof typeof fieldCatalog;

export const mvpFieldIds = Object.freeze(
  (Object.keys(fieldCatalog) as ResumeFieldId[]).filter(
    (fieldId) => fieldCatalog[fieldId].availability === 'mvp',
  ),
);

export const deferredFieldIds = Object.freeze(
  (Object.keys(fieldCatalog) as ResumeFieldId[]).filter(
    (fieldId) => fieldCatalog[fieldId].availability === 'deferred',
  ),
);

export function isResumeFieldId(value: string): value is ResumeFieldId {
  return Object.hasOwn(fieldCatalog, value);
}
